spring:
  application:
    name: seed

  profiles:
    active: local

  config:
    import:
      - optional:classpath:application-secret.yaml

jwt:
  access-token-expiration: 1800000 # 30분
  refresh-token-expiration: 1209600000 # 14일

logging:
  level:
    root: INFO
    com.sayyoung.seed: INFO